
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const K="sidelineiq_v013_corrected",OLD1="sidelineiq_v013",OLD2="sidelineiq_v012";
let S=(()=>{try{let raw=localStorage.getItem(K)||localStorage.getItem(OLD1)||localStorage.getItem(OLD2);let s=raw?JSON.parse(raw):{teams:[],games:[]};localStorage.setItem(K,JSON.stringify(s));return s}catch{return{teams:[],games:[]}}})();
let P={};const save=()=>localStorage.setItem(K,JSON.stringify(S)),uid=()=>crypto.randomUUID?.()||Date.now()+"";
const esc=s=>String(s||"").replace(/[&<>"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[x])),other=s=>s==="team"?"opp":"team",clamp=n=>Math.max(0,Math.min(100,Math.round(n))),fmt=n=>n===50?"50":n<50?`OWN ${n}`:`OPP ${100-n}`;
function shell(x){$("#app").innerHTML=`<header class="top"><img src="./assets/sidelineiq-logo.svg" alt="SidelineIQ Find Your Edge"><button class="btn" onclick="location.hash='#teams'">My Teams</button></header>${x}`}
function route(){let h=location.hash||"#teams";h.startsWith("#team/")?team(h.split("/")[1]):h.startsWith("#game/")?game(h.split("/")[1]):teams()}addEventListener("hashchange",route);
function teams(){shell(`<main class="page"><div class="hero"></div><div class="row spread"><div><small style="color:#8ceeff;letter-spacing:2px;font-weight:900">SIDELINE COMMAND CENTER</small><h1>My Teams</h1></div><button class="btn primary" id="add">+ Add Team</button></div><div class="teams">${S.teams.map(t=>`<div class="card team" data-t="${t.id}"><div><span class="sw" style="background:linear-gradient(135deg,${t.primary} 60%,${t.secondary} 60%)"></span><b>${esc(t.name)}</b></div><span>›</span></div>`).join("")||'<div class="card team">No teams yet.</div>'}</div></main>`);$("#add").onclick=()=>{let n=prompt("Team name");if(!n)return;S.teams.push({id:uid(),name:n,primary:"#5b21b6",secondary:"#f4c43d"});save();teams()};$$("[data-t]").forEach(x=>x.onclick=()=>location.hash="#team/"+x.dataset.t)}
function team(tid){let t=S.teams.find(x=>x.id===tid);if(!t)return teams();shell(`<main class="page"><div class="card team"><div><h2>${esc(t.name)}</h2><small>Football · SidelineIQ</small></div><button class="btn primary" id="addg">+ Add Game</button></div><div class="teams mt">${S.games.filter(g=>g.teamId===tid).map(g=>`<div class="card team" data-g="${g.id}"><div><b>${esc(g.opponent)}</b><div>${esc(g.date||"")} · ${esc(g.location||"Home")}</div></div><span>${g.teamScore||0}-${g.oppScore||0} ›</span></div>`).join("")||'<div class="card team">No games yet.</div>'}</div></main>`);$("#addg").onclick=()=>{let o=prompt("Opponent");if(!o)return;let teamKicks=confirm(`${t.name} kicks first?`),g={id:uid(),teamId:tid,opponent:o,date:new Date().toISOString().slice(0,10),location:"Home",oppColor:"#a77b18",teamScore:0,oppScore:0,period:1,down:1,toGo:10,los:20,poss:teamKicks?"opp":"team",plays:[],openingKick:teamKicks?"team":"opp",kickoffPending:true,kickoff:{phase:"kick",kicking:teamKicks?"team":"opp",receiving:teamKicks?"opp":"team",start:40,landing:null,end:null,kicker:"",returner:"",tacklers:[]}};S.games.push(g);save();location.hash="#game/"+g.id};$$("[data-g]").forEach(x=>x.onclick=()=>location.hash="#game/"+x.dataset.g)}
function side(g,t,s){return s==="team"?{name:t.name,color:t.primary}:{name:g.opponent,color:g.oppColor||"#a77b18"}}
function game(gid){let g=S.games.find(x=>x.id===gid),t=g&&S.teams.find(x=>x.id===g.teamId);if(!g||!t)return teams();g.plays??=[];g.teamScore??=0;g.oppScore??=0;P={type:"Run",end:g.los,score:null,def:[],pen:null};let a=side(g,t,"team"),b=side(g,t,"opp"),off=side(g,t,g.poss),def=side(g,t,other(g.poss));shell(`<main class="game">
<div class="score"><div class="teamScore" style="background:${a.color}">${esc(a.name)} <b>${g.teamScore}</b></div><div class="state">Q${g.period||1}<br>${g.kickoffPending?"KICKOFF":`${ordinal(g.down)} & ${g.toGo}`}<small>${g.kickoffPending?"Opening kick":fmt(g.los)}</small></div><div class="teamScore" style="background:${b.color}"><b>${g.oppScore}</b> ${esc(b.name)}</div></div>
<div class="gamebar"><div class="pill" style="background:${off.color}">${esc(off.name)} · Offense</div><div class="pill" style="background:${def.color}">${esc(def.name)} · Defense</div><button class="btn" id="period">Next Period</button><button class="btn" id="flip">Undo/Change Poss.</button><button class="btn danger" id="reset">Reset Game</button></div>
<div class="layout"><div class="card fieldCard"><div class="field" id="field"></div><div class="fieldcontrols"><div class="mini"><small>Ball at</small><b id="balltxt">${g.kickoffPending?"—":fmt(g.los)}</b></div><div class="mini"><small>Distance to 1st</small><b>${g.kickoffPending?"—":g.toGo}</b></div><div class="mini"><small>Down</small><b>${g.kickoffPending?"—":g.down}</b></div><div class="mini"><small>Yards to Go</small><b>${g.kickoffPending?"—":g.toGo}</b></div><div class="mini"><small>Period</small><b>Q${g.period||1}</b></div></div></div>
<aside class="card recent"><h3>Recent Plays</h3><div class="plays">${[...g.plays].reverse().map((p,i)=>`<div class="play">${g.plays.length-i}. ${esc(p.desc)}</div>`).join("")||'<div class="play">No plays yet.</div>'}</div><div class="row" style="padding:9px"><button class="btn" id="undo">Undo Last Play</button></div></aside></div>
<div class="work"><div class="pane"><div class="ph" style="background:${off.color}">OFFENSE</div><div class="pb">${g.kickoffPending?'<div class="note">Finish the opening kickoff in Special Teams.</div>':offPane()}</div></div><div class="pane"><div class="ph" style="background:${def.color}">DEFENSE</div><div class="pb">${defPane()}</div></div><div class="pane"><div class="ph penalty">PENALTY</div><div class="pb">${penPane()}</div></div><div class="pane"><div class="ph special">SPECIAL TEAMS</div><div class="pb">${stPane(g,t)}</div></div></div><div class="save"><button class="btn primary" id="savep">✓ Save Play</button></div>
</main>`);bind(g,t);draw(g,t)}
function offPane(){return `<h5>PLAY TYPE</h5><div class="seg" id="types"><button class="active">Run</button><button>Pass</button></div><div class="row mt">Player # <input id="player"></div><h5>RESULT / SCORING</h5><div class="seg"><button data-score="">Normal</button><button data-score="TD">Touchdown +6</button><button data-score="2PT">2-Point +2</button><button id="fumble">Fumble</button></div>`}
function defPane(){return `<div class="row">Player # <input id="dnum"></div><h5>ACTION</h5><div class="seg">${["Tackle","Assist","Missed","Pressure","Hurry"].map(x=>`<button data-def="${x}">${x}</button>`).join("")}</div><h5>SCORING</h5><div class="seg"><button data-dscore="Safety">Safety +2</button><button data-dscore="Def TD">Defensive TD +6</button></div><div id="dlist" class="mt"></div>`}
function penPane(){return `<div class="row"><select id="pside"><option>Offense</option><option>Defense</option></select><select id="ptype"><option>Holding</option><option>False Start</option><option>Delay of Game</option><option>Offside</option><option>Pass Interference</option><option>Personal Foul</option><option>Other</option></select><input id="pyd" type="number" value="10"></div><label><input type="checkbox" id="repeat"> Repeat down / no play</label><label><input type="checkbox" id="auto"> Automatic first down</label><button class="btn mt" id="attach">Attach Penalty</button><div id="psum" class="mt">No penalty attached.</div>`}
function stPane(g,t){if(g.kickoffPending){let k=g.kickoff;if(k.phase==="kick")return `<div class="steps">1 · KICK → 2 · RETURN</div><div class="note"><b>${esc(side(g,t,k.kicking).name)}</b> kicks from OWN 40. Enter the kicker, then drag the football to the landing/catch spot.</div><div class="row mt">Kicker # <input id="kicker"></div><div class="mt">Landing: <b>${k.landing==null?"drag football":fmt(k.landing)}</b></div><button class="btn primary mt" id="lock" ${k.landing==null?"disabled":""}>Lock Landing Spot →</button>`;return `<div class="steps">✓ KICK → 2 · RETURN</div><div class="note"><b>${esc(side(g,t,k.receiving).name)}</b> return. Field perspective is now the receiving team. Drag football to the end of the return.</div><div class="row mt">Returner # <input id="returner"> Tackler # <input id="tackler"><button class="btn" id="addt">Add</button></div><div class="mt">Return end: <b>${k.end==null?"drag football":fmt(k.end)}</b><br>Tacklers: ${k.tacklers.join(", ")||"—"}</div><button class="btn primary mt" id="finish" ${k.end==null?"disabled":""}>Finish Kickoff</button>`}return `<h5>SPECIAL TEAMS</h5><div class="seg"><button>Kickoff</button><button>Punt</button><button>Field Goal</button><button>PAT</button></div><div class="row mt">Kicker # <input id="stk"></div><div class="seg mt"><button>Good</button><button>No Good</button></div>`}
function bind(g,t){$("#period").onclick=()=>{g.period=(g.period||1)+1;save();game(g.id)};$("#flip").onclick=()=>{if(g.kickoffPending)return;g.poss=other(g.poss);g.los=100-g.los;g.down=1;g.toGo=10;save();game(g.id)};$("#reset").onclick=()=>{if(!confirm("Reset game?"))return;let k=g.openingKick||"team";Object.assign(g,{teamScore:0,oppScore:0,period:1,down:1,toGo:10,los:20,poss:k==="team"?"opp":"team",plays:[],kickoffPending:true,kickoff:{phase:"kick",kicking:k,receiving:other(k),start:40,landing:null,end:null,kicker:"",returner:"",tacklers:[]}});save();game(g.id)};$("#undo").onclick=()=>{let p=g.plays.pop();if(p){Object.assign(g,structuredClone(p.before));save();game(g.id)}};$("#savep").onclick=()=>savePlay(g);
if(g.kickoffPending){let k=g.kickoff;if($("#kicker"))$("#kicker").oninput=e=>{k.kicker=e.target.value;save()};if($("#lock"))$("#lock").onclick=()=>{k.phase="return";k.end=k.landing;save();game(g.id)};if($("#returner"))$("#returner").oninput=e=>{k.returner=e.target.value;save()};if($("#addt"))$("#addt").onclick=()=>{let n=$("#tackler").value;if(n)k.tacklers.push("#"+n);save();game(g.id)};if($("#finish"))$("#finish").onclick=()=>finishKO(g);return}
$$($("#types")? "#types button":"").forEach?.(b=>b.onclick=()=>{$$("#types button").forEach(x=>x.classList.remove("active"));b.classList.add("active");P.type=b.textContent});$$("[data-score]").forEach(b=>b.onclick=()=>P.score=b.dataset.score||null);$$("[data-dscore]").forEach(b=>b.onclick=()=>P.score=b.dataset.dscore);$$("[data-def]").forEach(b=>b.onclick=()=>{let n=$("#dnum").value;if(n)P.def.push("#"+n+" "+b.dataset.def);$("#dlist").textContent=P.def.join(", ")});$("#attach").onclick=()=>{P.pen={side:$("#pside").value,type:$("#ptype").value,y:+$("#pyd").value,repeat:$("#repeat").checked,auto:$("#auto").checked};$("#psum").textContent=`${P.pen.side} ${P.pen.type} ${P.pen.y} yd`}}
function snap(g){return{teamScore:g.teamScore,oppScore:g.oppScore,period:g.period,down:g.down,toGo:g.toGo,los:g.los,poss:g.poss,kickoffPending:g.kickoffPending,kickoff:g.kickoff?structuredClone(g.kickoff):null}}
function finishKO(g){let k=g.kickoff,b=snap(g),d=Math.abs(k.landing-k.start),r=Math.abs(k.end-k.landing);g.plays.push({before:b,desc:`Kickoff #${k.kicker||"—"} ${d} yd to ${fmt(k.landing)}; return #${k.returner||"—"} ${r} yd to ${fmt(k.end)}${k.tacklers.length?"; tackle "+k.tacklers.join(", "):""}`});g.poss=k.receiving;g.los=k.end;g.down=1;g.toGo=Math.min(10,100-g.los);g.kickoffPending=false;g.kickoff=null;save();game(g.id)}
function savePlay(g){if(g.kickoffPending)return alert("Finish kickoff first.");let b=snap(g),start=g.los,end=P.end,yd=end-start,pl=$("#player")?.value||"—",desc=`${P.type} #${pl} ${yd>=0?"+":""}${yd} yd`;if(P.score==="TD"){g[g.poss==="team"?"teamScore":"oppScore"]+=6;desc+=" · TOUCHDOWN"}if(P.score==="2PT"){g[g.poss==="team"?"teamScore":"oppScore"]+=2;desc+=" · 2-POINT GOOD"}if(P.score==="Safety"){g[other(g.poss)==="team"?"teamScore":"oppScore"]+=2;desc+=" · SAFETY"}if(P.score==="Def TD"){g[other(g.poss)==="team"?"teamScore":"oppScore"]+=6;desc+=" · DEFENSIVE TD"}if(P.def.length)desc+=` · ${P.def.join(", ")}`;if(P.pen)desc+=` · PEN ${P.pen.side} ${P.pen.type} ${P.pen.y}yd`;g.plays.push({before:b,desc});if(P.score==="TD"||P.score==="Def TD"){g.down=1;g.toGo=10;g.los=20}else if(P.pen?.repeat){g.los=end}else if(P.pen?.auto||yd>=g.toGo){g.los=end;g.down=1;g.toGo=Math.min(10,100-end)}else{g.los=end;g.toGo=Math.max(1,g.toGo-yd);g.down++;if(g.down>4){g.poss=other(g.poss);g.los=100-end;g.down=1;g.toGo=10}}save();game(g.id)}
function draw(g,t){let f=$("#field"),pers=g.kickoffPending?(g.kickoff.phase==="kick"?g.kickoff.kicking:g.kickoff.receiving):g.poss,l=side(g,t,pers),r=side(g,t,other(pers)),ball=g.kickoffPending?(g.kickoff.phase==="kick"?(g.kickoff.landing??g.kickoff.start):(g.kickoff.end??g.kickoff.landing)):g.los;let html=`<div class="ez" style="left:0;background:${l.color}">${esc(l.name)}</div><div class="ez r" style="background:${r.color}">${esc(r.name)}</div>`;for(let y=7;y<=93;y+=4.3){let major=Math.round((y-7)/4.3)%2===0;html+=`<div class="yard ${major?"major":""}" style="left:${y}%"></div>`}for(let p=14;p<93;p+=8.6){let n=Math.round((p-7)/.86);let v=n<=50?n:100-n;html+=`<div class="num top" style="left:${p}%">${v}</div><div class="num bottom" style="left:${p}%">${v}</div>`}for(let y=8;y<93;y+=.86)html+=`<div class="hash" style="left:${y}%"></div>`;if(!g.kickoffPending)html+=`<div class="line los" style="left:${7+g.los*.86}%"></div><div class="line fd" style="left:${7+clamp(g.los+g.toGo)*.86}%"></div>`;html+=`<div class="ball" id="ball" style="left:${7+ball*.86}%"></div>`;f.innerHTML=html;let drag=false,set=x=>{let q=f.getBoundingClientRect(),p=clamp(((x-q.left)/q.width*100-7)/.86);$("#ball").style.left=(7+p*.86)+"%";$("#balltxt")&&($("#balltxt").textContent=fmt(p));if(g.kickoffPending){if(g.kickoff.phase==="kick")g.kickoff.landing=p;else g.kickoff.end=p;save()}else P.end=p};$("#ball").onpointerdown=e=>{drag=true;$("#ball").setPointerCapture(e.pointerId)};$("#ball").onpointermove=e=>{if(drag)set(e.clientX)};$("#ball").onpointerup=e=>{drag=false;set(e.clientX);if(g.kickoffPending)game(g.id)}}
function ordinal(n){return n===1?"1st":n===2?"2nd":n===3?"3rd":n+"th"}
route();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
